### PR TITLE
Test "nightly" version of Python

### PR DESCRIPTION
**Pull request by myint**
This allows us to test the Python 3.5 related changes I made previously.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
:heart: :+1:

**Comment by bitglue** [comment]
:shipit:

**Comment by bitglue** [comment]
Since you are an owner now, I'll let you merge your own changes. No need to wait for me -- if the tests pass, you are satisfied with it, and one person has reviewed it, I think that's sufficient.

**Comment by myint** [comment]
Cool.

**Pull request merged**
