### PR TITLE
Update project metadata

### PR DESCRIPTION
**Pull request by bitglue**
Point people to GitHub, not Launchpad. All that's left on Launchpad are
a bunch of stale bugs.

Update the author field to reflect the large number of contributors.
Remove the maintainer field because a bug in something (setuptools?)
overwrites the author field with the maintainer field when the package
gets uploaded to PyPI.

### CODE REVIEW

**Comment by myint** [comment]
Can the GitHub issues page be enabled in this repository?

**Comment by bitglue** [comment]
@myint planning on it, as soon as I bug @florentx to add me to the launchpad project so I can clean that out.

**Comment by myint** [comment]
@bitglue, ping?

**Comment by bitglue** [comment]
Sorry, forgot about this thread. I did get access to Launchpad and did some grooming on the backlog there, but there's more to be done for sure. Would you like to help? If so, I can probably delegate the necessary privileges on GitHub and Launchpad to you.

**Comment by sigmavirus24** [comment]
@bitglue I'm happy to help as well.

**Comment by bitglue** [comment]
@myint @sigmavirus24 I've invited both of you to the Pyflakes organization on Github. It looks like we need some adjustment to the Launchpad permissions to allow you to do everything in the bug tracker, so I've reached out to @florentx for that, since he's the administrator there.

**Comment by myint** [comment]
Sounds good.

Thanks

**Comment by sigmavirus24** [comment]
@bitglue do we want to migrate the issues from LaunchPad to here? I can write a script to do so. (I've done the opposite direction already in a separate script.)

**Comment by bitglue** [comment]
It couldn't hurt. Besides the bug tracker, I don't think Launchpad is doing anything useful. If we migrate that, then we only need to maintain one thing.

**Comment by myint** [comment]
There seems to be an existing Launchpad-to-GitHub issue converter:

- https://github.com/termie/lp2gh
- https://github.com/termie/lp2gh/blob/master/docs/moving_issues.rst

**Comment by myint** [comment]
It's been over a year, but I finally tried exporting the issues from Launchpad using `lp2gh`.

https://gist.github.com/myint/df7b7f6a537a19b5a813a6d8b3cec52c

If someone enables the issues, I can use the same `lp2gh` tool to import the issues from the above JSON into this repository.

Here is a test import I did using a temporary repository:

https://github.com/myint/pyflakes-test/issues

**Comment by myint** [comment]
Note that Launchpad lists 53 open issues, but 2 of them actually have fixes committed. They were just left open. So it is correct for my test repository to have only 51 issues.

- https://bugs.launchpad.net/pyflakes/+bug/1506824
- https://bugs.launchpad.net/pyflakes/+bug/1624098

**Comment by jayvdb** [comment]
I've marked those two as 'Fix released'

**Comment by jayvdb** [comment]
The importer does add back ticks around `__future__`, and maybe some other conversions problems. 51 issues is low enough that IMO it is more sensible to edit the issues after import to fix any minor formatting issues.

**Comment by myint** [comment]
By the way, here is a version without labels for comparison:

https://github.com/myint/pyflakes-test-no-labels/issues

(The turnaround time for importing is a bit slow due to GitHub rate limiting.)

**Comment by myint** [comment]
One thing I probably want to avoid is using my own account to do the importing. Its fine for the temporary repository since I plan to delete it. But for the real permanent thing, I don't want to clutter up my personal ["issues" page](https://github.com/issues).

Pylint used a "bot" account when they imported their issues from BitBucket. I think it would make sense for me to do the same.

https://github.com/pylint-bot

**Comment by The-Compiler** [comment]
I did the issue migration there, let me know if I can help somehow. Using a bot account (with an alternative mail - if you have a gmail address, you should be able to use `yourmail+somelabel@gmail.com`) worked out fine.

**Comment by myint** [comment]
@The-Compiler Thanks! I'll let you know if I run into something.

**Comment by myint** [comment]
@bitglue Could you enable "issues" in this repository? Thanks.

**Comment by asmeurer** [comment]
@myint if you contact GitHub (and are really nice), they may help you do a "true" import, with correct usernames. We did this for sympy/sympy from Google Code a while back (see, e.g., https://github.com/sympy/sympy/issues/6000).

**Comment by myint** [comment]
@asmeurer Cool! Hopefully they have support for Launchpad.

**Comment by myint** [comment]
I'm guessing that would be the`my2` branch since it contains a new script:

https://github.com/skirpichev/google-code-issues-migrator/blob/my2/exportissues.py

It looks like that eventually got merged into a newer fork (https://github.com/abusalimov/google-code-issues-migrator/pull/1):

https://github.com/abusalimov/google-code-issues-migrator/blob/master/exportissues.py

The script outputs JSON files. Though, I didn't find any comments explicitly saying this was a format GitHub would accept.

**Comment by myint** [comment]
I just asked GitHub and got an immediate response from Shawna. They have an API for importing issues now. I think the `sympy/sympy` import happened years before this was released.

https://gist.github.com/jonmagic/5282384165e0f86ef105

It preserves the issue and comment dates. And it doesn't trigger notifications, so I won't have to worry about spamming watcher even if I add @ mentions.

I'll probably try this out in a test repository in a week or so.

**Comment by asmeurer** [comment]
Very nice. Good to know.

**Comment by myint** [comment]
Okay, here is an updated test using the GitHub import API:

https://github.com/pyflakes-bot/pyflakes-issue-import-test/issues

The issues and comments now have their original timestamps. They are owned by the new `pyflakes-bot` user I created since the API does not allow setting the commenter's username (for security).

**Comment by myint** [comment]
Here is a version with all the closed issues also included. They contain their proper timestamps for when they were closed.

https://github.com/pyflakes-bot/pyflakes-test-with-closed/issues

**Comment by myint** [comment]
The user importing the issues needs admin permissions:

https://gist.github.com/jonmagic/5282384165e0f86ef105#general-notes

I tested this out in the `pyflakes-test` organization. I gave `pyflakes-bot` admin permissions, ran my import script as `pyflakes-bot`, and then removed `pyflakes-bot`'s permissions.

https://github.com/pyflakes-test/issue-import-test/issues

**Comment by sigmavirus24** [comment]
@myint if you're ready to do this, I can manage the permissions wrangling etc.

**Comment by myint** [comment]
Great! I'm free right now.

**Comment by sigmavirus24** [comment]
Sorry @myint, I wasn't paying attention to this issue or my email. Let's schedule a time to do it? Perhaps it'd be easier to just email me with your availability so we don't spam folks here. We can report back with the final date/time

**Comment by myint** [comment]
https://github.com/PyCQA/pyflakes/issues

**Pull request merged**
